language: node_js
node_js:
    - "5"

before_script:
    - "npm run typings install"
    - "npm run build"

script:
    - "npm test"

deploy:
    provider: npm
    api_key: $NPMJS_COM_API_TOCKEN
    skip_cleanup: true
    on:
      all_branches: true